import { createFileRoute } from "@tanstack/react-router";

/**
 * PointPals theme tune — generated by ElevenLabs Music API.
 *
 * Public GET endpoint (bypasses auth) so the marketing site can play it.
 * The Worker caches an in-memory copy per instance; browsers cache for a day.
 * If ElevenLabs is temporarily unavailable, returns 503 so the client can
 * silently fall back to the built-in Web Audio chimes.
 */

const PROMPT = [
  "A short, warm, cozy family-brand theme jingle for a children's chore & kindness app called PointPals.",
  "Airy music-box and celeste playing a gentle pentatonic melody in C major — the notes C5 E5 G5 as a signature 'earned a point' chime, repeated as a hook.",
  "Soft glassy 'clink' percussion, like a glass marble dropping into a jar, on the off-beats.",
  "Add sparkly bell shimmer, tiny plucked ukulele and light hand-claps.",
  "Playful, joyful, tender — think Studio Ghibli meets Nintendo, never chiptune, no vocals, no dubstep, no drums beyond soft claps.",
  "Tempo around 96 BPM, ends resolved on a C major chord with a marble clink.",
].join(" ");

// Simple per-worker-instance memoisation so we don't re-bill on every hit.
let cached: { bytes: ArrayBuffer; ts: number } | null = null;
const CACHE_MS = 1000 * 60 * 60 * 12; // 12h

async function generate(): Promise<ArrayBuffer> {
  const key = process.env.ELEVENLABS_API_KEY;
  if (!key) throw new Error("ELEVENLABS_API_KEY not configured");
  const res = await fetch("https://api.elevenlabs.io/v1/music", {
    method: "POST",
    headers: {
      "xi-api-key": key,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      prompt: PROMPT,
      music_length_ms: 22000,
    }),
  });
  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(`ElevenLabs music ${res.status}: ${detail}`);
  }
  return res.arrayBuffer();
}

export const Route = createFileRoute("/api/public/theme-tune")({
  server: {
    handlers: {
      GET: async () => {
        try {
          if (!cached || Date.now() - cached.ts > CACHE_MS) {
            const bytes = await generate();
            cached = { bytes, ts: Date.now() };
          }
          return new Response(cached.bytes, {
            headers: {
              "Content-Type": "audio/mpeg",
              "Cache-Control": "public, max-age=86400, immutable",
            },
          });
        } catch (err) {
          console.error("theme-tune generation failed", err);
          return new Response("theme unavailable", { status: 503 });
        }
      },
    },
  },
});